Spotify_Auth/urls.py
from django.urls import path
from . import views_auth
from . import views_pages

app_name = 'main'

urlpatterns = [
    path('', views_auth.login_form),
    path('login', views_auth.login),
    path('login/redirect', views_auth.callback),

    path('welcome', views_pages.welcome, name='home'),
    path('search_playlist', views_pages.search_playlist, name='playlists'),
]

Spotify_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Spotify_Auth.urls')),
]

Spotify_Auth/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models.fields import TextField


class Credentials(models.Model):

    username = models.CharField(max_length=50, primary_key=True)
    access_token = models.TextField(unique=True)
    refresh_token = models.TextField(unique=True)
    scope = models.TextField()
    token_type = models.TextField()
    expires_in = models.DateTimeField()

    class Meta:
        db_table = 'credentials'


class PlaylistData(models.Model):

    username = models.ForeignKey(
        Credentials,
        on_delete=models.CASCADE,
    )
    playlist_id = models.TextField()
    playlist_name = models.TextField()
    playlist_url = models.TextField()
    playlist_uri = models.TextField()
    playlist_total_tracks = models.IntegerField(null=True, blank=True)
    playlist_public = models.BooleanField(null=True, blank=True)
    playlist_image = models.TextField(null=True, blank=True)


    class Meta:
        db_table = 'playlist_data'



class TracksData(models.Model):

    # user = models.ForeignKey(
    #     Credentials,
    #     on_delete=models.CASCADE,
    # )
    playlist = models.ForeignKey(
        PlaylistData,
        on_delete=models.CASCADE,
    )
    track_name = models.TextField()
    track_link = models.TextField()
    album_name = models.TextField()
    album_link = models.TextField()
    album_image = models.TextField()
    artist_name = ArrayField(models.TextField())
    artist_link = ArrayField(models.TextField())


    class Meta:
        db_table = 'tracks_data'

Spotify_Auth/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    remember_me = forms.BooleanField(required=False)

class ScanPlaylists(forms.Form):
    pass

Spotify_Auth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

import requests
from .credentials import CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, SCOPE

from .forms import LoginForm
from DataBase.firebase import DB_firebase as db
from .util import get_token


DB = db()



def welcome(request):
    token = get_token(request.session.get('username'))
    data = requests.get('https://api.spotify.com/v1/me/player/currently-playing', headers={
        'Authorization': f'Bearer {token}'
    }).json()
    context = {
        'username': request.session.get('username'),
        'token': token,
        'data': data
    }
    return render(request, 'welcome.html', context=context)


def authURL(request):
    url = requests.Request('GET', 'https://accounts.spotify.com/authorize', params={
            'scope': SCOPE,
            'response_type': 'code',
            'redirect_uri': REDIRECT_URI,
            'client_id': CLIENT_ID
        }).prepare().url
    return HttpResponseRedirect(url)



def callback(request):
    code = request.GET.get('code')
    
    response = requests.post('https://accounts.spotify.com/api/token', data={
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': REDIRECT_URI,
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET
    }).json()

    DB.set_user_data(request.session.get('username'), response)
    return redirect('/welcome')



def login_form(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            request.session['username'] = form.cleaned_data['username']
            # request.session['db'] = db

            # if DB.if_doc_exists(form.cleaned_data['username']):
            #     return HttpResponseRedirect('/welcome')
            return HttpResponseRedirect('/login')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

Spotify_Auth/templates/layout.html
<!DOCTYPE html>
<html>

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% load static %}
	{% if favicon_url %}
	<link rel="icon" href="{{ favicon_url }}" sizes="32x32" type="image/png">
	{% else %}
	<link rel="icon" href="static/images/favicon.png" sizes="32x32" type="image/png">
	{% endif %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'style_main.css' %}">

	{% if title %}
	<title>Spotify - {{ title }}</title>
	{% else %}
	<title>Spotify</title>
	{% endif %}

 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>  
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"></script>  
	<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css"/>  
</head>

<body>

	<ul class="tab">
		<a class="btn btn-dark" href="{% url 'main:home' %}">Home</a>
		<a class="btn btn-dark" href="{% url 'main:playlists' %}">Playlists</a>
		<!-- <button class="tablinks">LogOut</button> -->
	</ul>

	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<div class="page">
		{% block content %}{% endblock %}
	</div>
</body>

</html>

Spotify_Auth/templates/login.html
{% extends "layout.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

Spotify_Auth/templates/search_playlist.html
{% extends "layout.html" %}
{% block content %}

{% if scanForm %}
<form method="post" class="scan_form">
    {% csrf_token %}
    <div>
        <button id="scan_playlists" type="submit" name="scan" value="scan" class=
            "{% if scanBtnClass %} {{ scanBtnClass }} {% else %} btn btn-secondary {% endif %}">
            Scan Playlists
        </button>
    </div>
</form>
{% endif %}

<form method="post" class="search_form">
    {% csrf_token %}
    <div>
        <input type="text" id="tags" name="searchForm">
        <!-- {{ searchForm }} -->
        <button id="search_playlists" type="submit" name="search">Search</button>
    </div>
</form>


{% if search_tracks %}
{% if search %}
<h4 class="font-weight-bold text-center">{{ search }}</h4>
{% endif %}
<div class="card-columns">
    {% for track in search_tracks %}
        <div class="card text-white bg-dark mb-3 text-right" style="max-width: 18rem;">
            <img src="{{ track.playlist.playlist_image }}" class="card-img-top" width="300" height="300">
            <div class="card-body">
                <h6 class="card-title text-center">{{ track.playlist.playlist_name }}</h6>
                <div>
                    <img src="{{ track.album_image }}" width="50" height="50">
                    <a href="{{ track.album_link }}" target="_blank">{{ track.track_name }}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% elif playlist_data %}
<div class="card-columns">
    {% for pl_info in playlist_data %}
        <div class="card text-white bg-dark mb-3 text-right" style="max-width: 18rem;">
            <img src="{{ pl_info.playlist_image }}" class="card-img-top" width="300" height="300">
            <div class="card-body">
            <h6 class="card-title text-center">{{ pl_info.playlist_name }}</h6>
            <a href="{{ pl_info.playlist_url }}" class="btn btn-primary" target="_blank">Open PLaylist</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}

<!-- <script>
    $(function(){
        $('form.scan_form').on('submit', function(e){
            $('form.scan_form').append('<a class="font-weight-light" id="loading">Scanning Playlists...</a>')
        });
    })
</script> -->

<script>
    $( function() {
        var availableTags = JSON.parse("{{ tracks_list|escapejs }}");
        
      $( "#tags" ).autocomplete({
        source: availableTags,
        minLength: 2,
      });
    } );
</script>

{% endblock content %}

Spotify_Auth/templates/welcome.html
{% extends "layout.html" %}
{% block content %}

    <p style="text-align:center;">Welcome Lord <b style="color:darkgreen;">{{ username }}</b></p>
    {% if data %}
    <div class="flex-container" id="player">
        <a name="album_img"><img src={{data.item.album.images.1.url}} width="300" height="300"></a>
        <a name="song" href={{data.item.external_urls.spotify}}>{{data.item.name}}</a>
        {% for artists in data.item.artists %}
        <a name="artist" href={{artists.external_urls.spotify}}>{{artists.name}}</a>
        {% endfor %}
        <a name="album" href={{data.item.album.external_urls.spotify}}>{{data.item.album.name}}</a>
        <a name="playlist" href={{data.context.external_urls.spotify}}>Playlist</a>
    </div>
    {% else %}
    <p>{{ error }}</p>
    {% endif %}
    
{% endblock content %}